name: Release

# gh workflow run release.yml --ref <branch> -f tag=<tag>

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.tool-versions'

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: Build all files
        run: yarn build

      - name: Generate tarball
        run: |
          pushd packages/web
          yarn pack --out ../../%s.tgz
          popd
          pushd packages/worker
          yarn pack --out ../../%s.tgz
          popd

      - name: Create Tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -f -a ${{ inputs.tag }} -m "Release ${{ inputs.tag }}"
          git push -f origin ${{ inputs.tag }}

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            *.tgz
